### ISSUE TITLE
Missing commit history?

### ISSUE THREAD

**Issue by jc-dgit** [blind-oracle/go-radius#2]
Looking at this repo, it's README mentions it's a clone of https://github.com/layeh/radius.

It seems like the complete commit history for that repo has been removed though. 😦

Kind of wondering why, as the commit history is kind of useful when looking back through prior changes. :smile:

**Comment by blind-oracle** [comment]
Hi, well, this was copied at some point locally, reworked and then re-uploaded as a new repo, so the history was lost sadly.

I'm not working with RADIUS for about 5 years already so this is a kind of abandonware right now, use at your own risk :)

**Comment by jc-dgit** [comment]
k, no worries. :smile:
